
# Group V1

## /api/v1/payment_tags

### Get Payment Tags [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            [
                {
                    "id": 1,
                    "paymentId": 4,
                    "tagId": 1
                },
                {
                    "id": 2,
                    "paymentId": 8,
                    "tagId": 1
                },
                {
                    "id": 3,
                    "paymentId": 7,
                    "tagId": 13
                },
                {
                    "id": 4,
                    "paymentId": 5,
                    "tagId": 10
                },
                {
                    "id": 5,
                    "paymentId": 8,
                    "tagId": 9
                },
                {
                    "id": 6,
                    "paymentId": 6,
                    "tagId": 9
                },
                {
                    "id": 7,
                    "paymentId": 9,
                    "tagId": 13
                },
                {
                    "id": 8,
                    "paymentId": 3,
                    "tagId": 3
                },
                {
                    "id": 9,
                    "paymentId": 6,
                    "tagId": 4
                },
                {
                    "id": 10,
                    "paymentId": 4,
                    "tagId": 3
                }
            ]        


### Post Payment Tag [POST]


+ Request (application/x-www-form-urlencoded)



    + Body

            paymentId=7777&tagId=9999        

+ Response 201 (application/json; charset=UTF-8)



    + Body

            {
                "id": 11,
                "paymentId": 7777,
                "tagId": 9999
            }        



## /api/v1/payment_tags/{paymentTagId}

+ Parameters
    + paymentTagId: `1` (number)

### DELETE [DELETE]


+ Response 204 

### Get Payment Tag [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "id": 10,
                "paymentId": 4,
                "tagId": 3
            }        


### Update Payment Tag [PUT]


+ Request (application/json)



    + Body

            {
                "paymentId": 7777,
                "tagId": 9999
            }        

+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "id": 1,
                "paymentId": 7777,
                "tagId": 9999
            }        



## /api/v1/payments

### Get Payments [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            [
                {
                    "id": 1,
                    "placeId": 1,
                    "cost": 1000
                },
                {
                    "id": 2,
                    "placeId": 2,
                    "cost": 2000
                },
                {
                    "id": 3,
                    "placeId": 3,
                    "cost": 3000
                },
                {
                    "id": 4,
                    "placeId": 4,
                    "cost": 4000
                },
                {
                    "id": 5,
                    "placeId": 5,
                    "cost": 5000
                },
                {
                    "id": 6,
                    "placeId": 6,
                    "cost": 6000
                },
                {
                    "id": 7,
                    "placeId": 7,
                    "cost": 7000
                },
                {
                    "id": 8,
                    "placeId": 8,
                    "cost": 8000
                },
                {
                    "id": 9,
                    "placeId": 9,
                    "cost": 9000
                },
                {
                    "id": 10,
                    "placeId": 10,
                    "cost": 10000
                }
            ]        


### Post Payment [POST]


+ Request (application/x-www-form-urlencoded)



    + Body

            cost=9999&placeId=7777        

+ Response 201 (application/json; charset=UTF-8)



    + Body

            {
                "id": 11,
                "placeId": 7777,
                "cost": 9999
            }        



## /api/v1/payments/{paymentId}

+ Parameters
    + paymentId: `1` (number)

### DELETE [DELETE]


+ Response 204 

### Get Payment [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "id": 1,
                "placeId": 1,
                "cost": 1000
            }        


### Update Payment [PUT]


+ Request (application/json)



    + Body

            {
                "placeId": 7777,
                "cost": 9999
            }        

+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "id": 1,
                "placeId": 7777,
                "cost": 9999
            }        



## /api/v1/tags

### Get Tags [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            [
                {
                    "id": 1,
                    "tagName": "電気代"
                },
                {
                    "id": 2,
                    "tagName": "食費"
                },
                {
                    "id": 3,
                    "tagName": "家賃"
                },
                {
                    "id": 4,
                    "tagName": "水道代"
                },
                {
                    "id": 5,
                    "tagName": "ガス代"
                },
                {
                    "id": 6,
                    "tagName": "交通費"
                },
                {
                    "id": 7,
                    "tagName": "酒代"
                },
                {
                    "id": 8,
                    "tagName": "飲み物代"
                },
                {
                    "id": 9,
                    "tagName": "雑費"
                },
                {
                    "id": 10,
                    "tagName": "菓子代"
                },
                {
                    "id": 11,
                    "tagName": "電化製品"
                },
                {
                    "id": 12,
                    "tagName": "服代"
                },
                {
                    "id": 13,
                    "tagName": "本代"
                },
                {
                    "id": 14,
                    "tagName": "通信代"
                },
                {
                    "id": 15,
                    "tagName": "医療費"
                }
            ]        


### Post Tag [POST]


+ Request (application/x-www-form-urlencoded)



    + Body

            tagName=test+tag        

+ Response 201 (application/json; charset=UTF-8)



    + Body

            {
                "id": 16,
                "tagName": "test tag"
            }        



## /api/v1/tags/{tagId}

+ Parameters
    + tagId: `1` (number)

### DELETE [DELETE]


+ Response 204 

### Get Tag [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "id": 1,
                "tagName": "電気代"
            }        


### Update Tag [PUT]


+ Request (application/json)



    + Body

            {
                "tagName": "updated tag"
            }        

+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "id": 1,
                "tagName": "updated tag"
            }        



## /api/v1/users/{userId}

+ Parameters
    + userId: `1` (number)

### User Show [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            {
                "ID": 1,
                "UserName": "testuser1"
            }        



## /api/v1/users{?pagination}

+ Parameters
    + pagination: `false` (boolean)

### User Index [GET]


+ Response 200 (application/json; charset=UTF-8)



    + Body

            [
                {
                    "ID": 0,
                    "UserName": "testuser0"
                },
                {
                    "ID": 1,
                    "UserName": "testuser1"
                },
                {
                    "ID": 2,
                    "UserName": "testuser2"
                },
                {
                    "ID": 3,
                    "UserName": "testuser3"
                },
                {
                    "ID": 4,
                    "UserName": "testuser4"
                },
                {
                    "ID": 5,
                    "UserName": "testuser5"
                },
                {
                    "ID": 6,
                    "UserName": "testuser6"
                },
                {
                    "ID": 7,
                    "UserName": "testuser7"
                },
                {
                    "ID": 8,
                    "UserName": "testuser8"
                },
                {
                    "ID": 9,
                    "UserName": "testuser9"
                }
            ]        


